### ISSUE TITLE
Fails to Extract Concatenated Strings in defineMessages

### ISSUE THREAD

**Issue by archy-bold** [bang88/typescript-react-intl#35]
When I use a concatenated string in `defineMessages` for `defaultMessage`, that message isn't picked up by the plugin.

eg

```
const messages = defineMessages({
    message: {
        id: "mesage.id",
        defaultMessage: "Message over"
            + " multiple lines",
    },
});
```

**Comment by archy-bold** [comment]
Had a look and the node is a `BinaryExpression`. I don't know much about TypeScript. How would you go about evaluation an Expression node to find if it's text?

**Comment by BANG88** [comment]
Why don't you using a multiple line string instead of a concatenated string.

eg:
```js
`Message over
 multiple lines
other`
```

**Comment by archy-bold** [comment]
Ok, that works.
