### ISSUE TITLE
Messages defined inside arrow functions are not pickedup

### ISSUE THREAD

**Issue by ghost** [bang88/typescript-react-intl#36]
Messages which are defined using defineMessages inside arrow functions are not extracted.
```
const sample = () => {
const sampleMessage = defineMessage ({
title: {
id: "sample.id",
defaultMessage: "sample.message"
}
});
```

**Comment by BANG88** [comment]
The usage looks really strange. Can you tell me what do you want ? I think most use case are just define some messages and use it directly.
