### ISSUE TITLE
Not parsing FormattedMessage if no defaultMessage is defined

### ISSUE THREAD

**Issue by ilan-schemoul** [bang88/typescript-react-intl#39]
As the title says a component with both id and defaultMessage is picked up, if only attr id is defined the component is ignored. defaultMessage is not mandatory by any mean, and I don't see the point of putting one as it will just be the same as what I write in the english locale file.

**Comment by ilan-schemoul** [comment]
#40 fixes it.

**Comment by BANG88** [comment]
Please ping me if you wait too long.  Thanks
