### ISSUE TITLE
0.15 changes Typescript version

### ISSUE THREAD

**Issue by jwulf** [bang88/typescript-react-intl#5]
Hi, love your work.

In 0.14, you installed typescript as a peer dependency like this:

```
 "typescript": "^2.0.10"
```

In 0.15, you install it like this:

```
 "typescript": "2.0.10"
```

This breaks a bunch of my stuff in weird ways. I get errors about `yield being a keyword`. 

I'm working around it by installing typescript explicitly at 2.2.0. I need 0.15 of this package for the fix to issue #4. 

Could you unlock the typescript peer dependency version in 0.15?

**Comment by BANG88** [comment]
I am sorry for this change, i need test the latest typescript api. if it works as expected i will publish a new version.  Thank you.

**Comment by BANG88** [comment]
@jwulf please test the latest version
