### ISSUE TITLE
Support formatMessage api

### ISSUE THREAD

**Issue by baktun14** [bang88/typescript-react-intl#6]
Hi, thanks for putting this together!

I think it would be great to add formatMessage into the mix since it's basically the same as `FormattedMessage`.

**Comment by BANG88** [comment]
Did you mean parse `formatMessage` method ? I personally don't use this method, PR are welcome :)

**Comment by baktun14** [comment]
Yea that's what I meant, I will try to do this this week-end

**Comment by BANG88** [comment]
fixed by https://github.com/bang88/typescript-react-intl/commit/1609c18d16f81a0a214e3f46715bdb4f408c718f
